################################################################################## Version: @version@
# +--------------â–„â–„â–„-- â€šâ€”â€”. -â–„--â–„-â–„--â–„-â–„-â–„â–„â–„â–„â–„---------------------------------------------------+ #
# |              â–ˆâ–„â–„â–€ (â€œâ€¡â€¡â€) â–ˆâ–„â–„â–€ â–ˆâ–„â–„â–€ â–ˆ   â–ˆ         Support available at: discord.gg/mTaHuK6BVa | #
# |              â–ˆâ–„â–„â–ˆ  \__/  â–ˆ  â–ˆ â–ˆ  â–ˆ â–ˆ   â–ˆ                    â€š-.                              | #
# |         â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€” ((_)) â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”          | #
# |                                                             â€˜-â€™                              | #
# |         .|'''.|  |''||''|     |     '||''|.    ..|'''.|      |     |''||''| '||''''|         | #
# |         ||..  '     ||       |||     ||   ||  .|'     '     |||       ||     ||  .           | #
# |          ''|||.     ||      |  ||    ||''|'   ||    ....   |  ||      ||     ||''|           | #
# |        .     '||    ||     .''''|.   ||   |.  '|.    ||   ;â€™   |.     ||     ||              | #
# |         '....|'    .||.   .|.  .||. .||.  '|'  ''|...'|  .|.  .||.   .||.   .||.....|        | #
# +----------------------------------------------------------------------------------------------+ #
# |                        https://spigotmc.org/resources/stargate.87978/                        | #
# +----------------------------------------------+-----------------------------------------------+ #
# |      Documentation: https://git.io/JDclf     |       Bug Reports: https://git.io/Jc6jW       | #
# +----------------------------------------------+-----------------------------------------------+ #
####################################################################################################


# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# What language will stargate use when communicating with your users?
# Supported values: [en,de,nl,no,nn,sv,zh,cs,fr,tr]
#
# If SG isn't yet available in your language, please consider becoming a translator:
# https://crowdin.com/project/stargate-bukkit
language: en

bungee:
  # Are you connected to a bungee-compatible proxy?
  # Set this to true if you intend on building gates with the 'u' flag.
  usingBungee: false


  # By default, StarGate uses a local SQLite database to store its data.
  #
  # If you are running a large server, we recommend using a remote database.
  # Note that such a database is required if you intend on building gates with the 'i' flag.
  useRemoteDatabase: false


  # Only applicable if useRemoteDatabase is true.
  remoteDatabaseSettings:
    # What driver should stargate use to connect to your database?
    # Currently, these are supported: [MySQL, MariaDB]
    driver: MySQL

    # Where can stargate find your database?
    address: localhost
    port: 3306

    # Should stargate use SSL when connecting to your database?
    useSSL: true

    # The name of the database StarGate will use to store its data. Must already exist.
    # If you are using Bungee, this should be shared across all StarGate instances.
    database: stargate


    # Credentials to use for the connection:
    username: root
    password: ''

    # Should we generate a database config file ('hikari.properties') in your stargate folder?
    # Doing so will ignore all the remoteDatabaseSettings above in favour of the new file!
    #
    # This allows you to use advanced RDMS features such as pool limits, cache sizes, etc.
    # A list of available settings can be found at this link: https://git.io/J1hua.
    advancedDatabaseConfiguration: false

# What network will be used when none has been specified? (Max length 12 characters)
#
# Note that this primarily applies to users with the stargate.create.network node.
# Generally, that node is given to staff (we recommend stargate.create.personal for users).
defaultGateNetwork: central

# What network will StarGate reserve for terminal ('T') portals?
#
# Generally, this feature is used to make a group of portals in spawn known as a 'Terminal'.
# Using this network, players can pay to connect their towns/bases/shops/etc. to the terminal.
#
# â€¦Â«Â«Â»Â»â€¦  Not yet implemented!
# â€œNOTEâ€  Terminal support is slated for 1.1.0.0!
defaultTerminalNetwork: terminal


# +----------------------------------------------------------------------------------------------+ #
# |                                        Gate Behaviour                                        | #
# +----------------------------------------------------------------------------------------------+ #

# What is the maximum number of gates a single network may contain? (-1 for unlimited)
networkLimit: -1

# Will vehicles and their passengers be able to travel through StarGate portals?
#  [minecarts, boats, & saddled mobs = vehicles | players & mobs = passengers]
handleVehicles: true

# If a player teleports while attached with a lead to an entity, should SG also teleport the entity?
handleLeashedCreatures: true

# Will the server re-verify all existing portals on startup?
# 
# This checks that the expected gates are both present and using a valid layout.
# Designed to catch .gate file modifications, world changes, and terrain regeneration.
# 
# â€¦Â«Â«Â»Â»â€¦  If you set this to true, you should ensure protectEntrance (below) is set to true!
# â€œNOTEâ€  Otherwise, disallowed players, block updates, and snowmen can invalidate your portals!
checkPortalValidity: true

# SG protects gate ğ‘“ğ‘Ÿğ‘ğ‘šğ‘’ materials; should it also protect gate ğ‘ğ‘ğ‘’ğ‘Ÿğ‘¡ğ‘¢ğ‘Ÿğ‘’ (open/closed) materials?
# ex. in nether.gate, should nether_portal be protected?
protectEntrance: true

# Can StarGates be broken via an explosion?
#  [tnt, creepers, etc.]
destroyOnExplosion: false


# +----------------------------------------------------------------------------------------------+ #
# |                                            Economy                                           | #
# +----------------------------------------------------------------------------------------------+ #

# Will StarGate interact with your server's economy?
# 
#  â€¦Â«Â«Â»Â»â€¦  For these features, StarGate depends on the Vault plugin.
#  â€œNOTEâ€  https://www.spigotmc.org/resources/vault.34315/
useEconomy: false

# Does your server have a tax account (closed economy)?
# If so, please provide the name of your tax account (collected money will be sent to it).
# If not, leave this section blank (collected money will be deleted).
# 
# Note that usageCost money is excluded from this system when gateOwnerRevenue is true.
taxAccount: ""

# How much will be deducted from players' accounts when creating a new gate?
creationCost: 0

# How much will be deducted from players' accounts when destroying an existing gate?
destructionCost: 0

# How much will be deducted from players' accounts when using a stargate to teleport?
# This does not apply to stargates with the 'f' flag.
usageCost: 0

# Will fees collected for â€˜usecostâ€™ be paid to whomever created (owns) the applicable stargate?
# If false, collected funds will be deleted (or sent to the taxAccount).
gateOwnerRevenue: true

# Will â€˜creationCostâ€™ still be charged if the new gate's destination is a gate with the 'f' flag?
# Note that this only applies to fixed gates.
chargeFreeDestination: true


# +----------------------------------------------------------------------------------------------+ #
# |                                       Aesthetic Tweaks                                       | #
# +----------------------------------------------------------------------------------------------+ #

# What colour will StarGate use for all text when formatting gate signs?
# Note that players can override this with DYE and/or GLOW_INK_SAC
#
# All colour names should follow this format:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Color.html#field.summary
signStyle:
  defaultForeground: BLACK
  defaultBackground: WHITE
  # [1: foreground, 2: gate type, 3: grey, 4: background]
  pointer: 2
  # [1: selected gates coloured, 2: all gates coloured, 3: no gates coloured]
  listing: 1

# By default, SG allows users to specify coloured names for their gates via external plugins.
# Such names override the colours specified for signStyle (above).
#
# Should SG disable this behaviour by forcing the game to display exactly what was written?
disableCustomColoredNames: false

# Will the destination a networked portal last connected to be listed first in its scroll menu?
rememberLastDestination: false

# At what speed should players be sent out of portals?
# When exiting a gate, players retain their original movement velocity, multiplied by this value.
gateExitSpeedMultiplier: 1

# +----------------------------------------------------------------------------------------------+ #
# |                                           Technical                                          | #
# +----------------------------------------------------------------------------------------------+ #

# |                                       [ Compatibility ]                                      | #
# |__      These settings are provided to improve SG 10's interactions with other plugins.     __| #

# When useRemoteDatabase is false, Stargate stores all of its portal data in a flatfile.
# Where should this flatfile be named?
portalFile: stargate

# By default, SG will preface its remote database tables with `SG_`.
# If this conflicts with another plugin, you can change that prefix here.
customRemoteDatabasePrefix: SG_

# |                                          [ Logging ]                                         | #
# |__                   How much information should stargate send to console?                  __| #

# Possible Values:
#   |=> SEVERE (Not recommended).
#   |   - ğ‡ğ¢ğğ ğğ¯ğğ«ğ²ğ­ğ¡ğ¢ğ§ğ . ğ‘‚ğ‘›ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘–ğ‘›ğ‘¡ ğ‘¡ğ‘œ ğ‘ğ‘œğ‘›ğ‘ ğ‘œğ‘™ğ‘’ ğ‘–ğ‘“ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘› ğ‘“ğ‘ğ‘¡ğ‘ğ‘™ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘ğ‘ â„ğ‘’ğ‘ 
#   |=> WARNING (Recommended for large and well-tested production implementations).
#   |   - ğ‡ğ¢ğğ ğ§ğ¨ğ«ğ¦ğšğ¥ ğ›ğğ¡ğšğ¯ğ¢ğ¨ğ®ğ«. ğ‘‚ğ‘›ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘–ğ‘›ğ‘¡ ğ‘ğ‘œğ‘¡ğ‘’ğ‘›ğ‘¡ğ‘–ğ‘ğ‘™ ğ‘–ğ‘ ğ‘ ğ‘¢ğ‘’ğ‘ .
#   |=> INFO (Recommended for most production implementations).
#   |   - ğğ«ğ¢ğ§ğ­ ğ§ğ¨ğ«ğ¦ğšğ¥ ğ›ğğ¡ğšğ¯ğ¢ğ¨ğ®ğ«. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘ğ‘œğ‘Ÿğ‘¡ğ‘ğ‘™ ğ‘’ğ‘£ğ‘’ğ‘›ğ‘¡ğ‘  (ğ‘¢ğ‘ ğ‘ğ‘”ğ‘’, ğ‘ğ‘Ÿğ‘’ğ‘ğ‘¡ğ‘–ğ‘œğ‘›, ğ‘‘ğ‘’ğ‘ ğ‘¡ğ‘Ÿğ‘¢ğ‘ğ‘¡ğ‘–ğ‘œğ‘›, ğ‘’ğ‘¡ğ‘.)
#   |=> CONFIG (Useful for configuring preproduction instances).
#   |   - ğğ«ğ¢ğ§ğ­ ğ©ğğ«ğ¦ğ¢ğ¬ğ¬ğ¢ğ¨ğ§ ğœğ¡ğğœğ¤ğ¬. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘â„ğ‘’ğ‘ğ‘˜ğ‘  ğ‘šğ‘ğ‘‘ğ‘’ ğ‘¡ğ‘œ ğ‘‘ğ‘’ğ‘¡ğ‘’ğ‘Ÿğ‘šğ‘–ğ‘›ğ‘’ ğ‘–ğ‘“ ğ‘ğ‘™ğ‘ğ‘¦ğ‘’ğ‘Ÿğ‘  ğ‘ğ‘ğ‘› ğ‘ğ‘’ğ‘Ÿğ‘“ğ‘œğ‘Ÿğ‘š ğ‘ğ‘› ğ‘ğ‘ğ‘¡ğ‘–ğ‘œğ‘›.
#   |=> FINE (Recommended for basic troubleshooting).
#   |   - ğğ«ğ¢ğ§ğ­ ğ¥ğ¢ğ¦ğ¢ğ­ğğ ğğğ›ğ®ğ  ğ¢ğ§ğŸğ¨. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘”ğ‘’ğ‘›ğ‘’ğ‘Ÿğ‘ğ‘™ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘› ğ‘’ğ‘£ğ‘’ğ‘›ğ‘¡ğ‘  (ğ‘™ğ‘œğ‘ğ‘‘ğ‘–ğ‘›ğ‘”, ğ‘‘ğ‘–ğ‘ ğ‘ğ‘ğ‘™ğ‘–ğ‘›ğ‘”, ğ‘ğ‘œğ‘›ğ‘›ğ‘’ğ‘ğ‘¡ğ‘–ğ‘œğ‘›ğ‘ , ğ‘’ğ‘¡ğ‘.).
#   |=> FINER (Recommended for some addon developers).
#   |   - ğğ«ğ¢ğ§ğ­ ğ¦ğ¨ğ¬ğ­ ğğğ›ğ®ğ  ğ¢ğ§ğŸğ¨. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘šğ‘’ğ‘ ğ‘ ğ‘ğ‘”ğ‘’ğ‘  ğ‘‘ğ‘’ğ‘¡ğ‘ğ‘–ğ‘™ğ‘–ğ‘›ğ‘” ğ‘¡â„ğ‘’ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘›'ğ‘  ğ‘™ğ‘œğ‘”ğ‘–ğ‘ ğ‘ğ‘›ğ‘‘ ğ‘ğ‘’â„ğ‘ğ‘£ğ‘–ğ‘œğ‘¢ğ‘Ÿ.
#   |=> FINEST (Only used by StarGate's core development team).
#   |   - ğğ«ğ¢ğ§ğ­ ğğ¯ğğ«ğ²ğ­ğ¡ğ¢ğ§ğ . ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘™ğ‘–ğ‘¡ğ‘’ğ‘Ÿğ‘ğ‘™ğ‘™ğ‘¦ ğ‘’ğ‘£ğ‘’ğ‘Ÿğ‘¦ğ‘¡â„ğ‘–ğ‘›ğ‘”, ğ‘–ğ‘›ğ‘ğ‘™ğ‘¢ğ‘‘ğ‘–ğ‘›ğ‘” ğ‘›ğ‘¢ğ‘šğ‘’ğ‘Ÿğ‘œğ‘¢ğ‘  ğ‘ ğ‘¡ğ‘ğ‘ğ‘˜ ğ‘¡ğ‘Ÿğ‘ğ‘ğ‘’ğ‘ .
loggingLevel: INFO

# |                                           [ Debug ]                                          | #
# |__     These settings are provided to help developers diagnose issues with this plugin.     __| #

# An internal value used by the plugin to determine how old your config is.
# Please do not change this.
configVersion: 6
